### ISSUE TITLE
LICENSE file needs year and name of copyright owner 

### ISSUE THREAD

**Issue by folkengine** [smartcitiesdata/smartcitiesdata#309] opened 2019-11-08 16:38 UTC
See http://www.apache.org/foundation/license-faq.html#Apply-My-Software

**Comment by carriebrinkley** [comment] 2019-11-21 19:36
@folkengine, is this a duplicate of #264 or did you mean to link something else?

**Comment by jdenen** [comment] 2019-11-21 20:35
This was originally opened in another repo, but it was moved here ahead of migrating that app to the umbrella. This can be closed in favor of #264.

**Closed by jdenen** 2019-11-21 20:35 UTC
