### ISSUE TITLE
Username is required to be the same as the Database name

### ISSUE THREAD

**Issue by JShefferPillar** [smartcitiesdata/smartcitiesdata#297] opened 2019-11-04 17:54 UTC
https://github.com/smartcitiesdata/discovery_api/blob/790542c029be0dcffaeeda87d4b715a252c2597e/rel/runtime.exs#L28

**Comment by rob-h-m** [comment] 2019-11-14 16:48
I would contend that "this works with Azure" is a new requirement, not a bug.

If it was an existing requirement, then there should have been a prior card that called this out as an AC, tests written to verify it works, etc.

**Comment by jdenen** [comment] 2019-11-14 17:52
The bug was not that it didn't work with Azure. That's just what led us to discover it.

The bug is that we force the user and database to be the same value. That's generally a bad idea and forcing users to do this is a bug.

We could have easily changed the DB name or database in AWS and run into this same bug. But we worked around the bug at the infrastructure level because we could. You cannot do that same workaround in Azure.

**Comment by rob-h-m** [comment] 2019-11-14 17:54
Thanks for clarifying

**Comment by jeffgrunewald** [comment] 2019-11-18 15:05
handled by https://github.com/smartcitiesdata/discovery_api/pull/291

**Comment by rob-h-m** [comment] 2019-12-13 18:31
@jdenen  @JShefferPillar This has appeared to be in progress for a while now - is it still active?  Thanks for any updates

**Comment by rob-h-m** [comment] 2019-12-30 14:56
@jdenen @JShefferPillar Anyone? @Bueller? Anyone?

**Comment by rob-h-m** [comment] 2020-01-06 14:51
@jdenen @JShefferPillar Happy New Year!  Is anyone actually working on this?  It has been "in progress" since before Thanksgiving.  Thank you.

CC @JarredOlson @carriebrinkley

**Comment by jeffgrunewald** [comment] 2020-01-06 15:10
According to @jdenen it is complete and ready to be merged/marked done but he is having us to do that to prevent us from taking anything to prod we aren’t ready for.

**Comment by rob-h-m** [comment] 2020-01-06 15:12
Thanks @jeffgrunewald I will get it on the wall and we can discuss at standup tomorrow.

**Closed** 2020-01-09 21:00 UTC
Labels: bug
